### ISSUE TITLE
fix link in the "MDA team wiki" (navbar)

### ISSUE THREAD

**Issue by defuneste** [ruralinnovation/wiki#54]
the "MDA team wiki" link to https://ruralinnovation.github.io/wiki/index.md and not the corresponding html file ... (I will drop an issue, one of us can fix that later), prob a trouble in _quarto.yml

**Comment by tech-team-rural-mda** [comment]
It looks like quarto was having an issue rendering `README.qmd` with this include statement...
```

{{< include README.qmd >}}

````
