### ISSUE TITLE
mermaid in quarto and gh markdown

### ISSUE THREAD

**Issue by defuneste** [ruralinnovation/wiki#6]
We need to find a way to change mermaid chunck code. Currently the mermaid chunck are set up for rendering in github but fail if we ask it to be rendering by quarto

**Comment by tech-team-rural-mda** [comment]
I think rendering mermaid in quarto is not supported by `md` => `website` projects. Would it work if we turned all the `md` files into `qmd`?

**Comment by defuneste** [comment]
@tech-team-rural-mda yes it will, good idea!

**Comment by defuneste** [comment]
@dancingfrog I am closing this one, I think having the mermaid graph in rendering the html is good enough, take priority, and not having it while in md mode from GH is not a big deal.
